import { RequestMiddlewareRegistration, ResponseMiddlewareRegistration } from "../lib/router/middlewareRegistration";
import { getCTMSubdomain, SubdomainInfo } from "../utils.js";

// wordpress cf page routes are handled outside of ctm.ts to keep them logically housed in one place
const greedyRoutes = {
  staticContentRoute: "/static-content/",
  preProdRoute: "/pre-prod/"
};

const singletonRoutes = {
  baseRoute: "/"
};

const newTrancheRoutes = [
  "/about-us/",
  "/business-insurance/",
  "/car-insurance/",
  "/car-insurance/4x4-insurance/",
  "/car-insurance/accidents/",
  "/car-insurance/agreed-value-vs-market-value/",
  "/car-insurance/australia/",
  "/car-insurance/australia/act/",
  "/car-insurance/australia/new-south-wales/",
  "/car-insurance/australia/new-south-wales/sydney/",
  "/car-insurance/australia/northern-territory/",
  "/car-insurance/australia/queensland/",
  "/car-insurance/australia/queensland/brisbane/",
  "/car-insurance/australia/south-australia/",
  "/car-insurance/australia/south-australia/adelaide/",
  "/car-insurance/australia/tasmania/",
  "/car-insurance/australia/victoria/",
  "/car-insurance/australia/victoria/melbourne/",
  "/car-insurance/australia/western-australia/",
  "/car-insurance/australia/western-australia/perth/",
  "/car-insurance/business-car/",
  "/car-insurance/calculator/",
  "/car-insurance/car-brands/",
  "/car-insurance/car-breaks-down/",
  "/car-insurance/cheap-australia/",
  "/car-insurance/classic/",
  "/car-insurance/classic/types/prestige-car-insurance/",
  "/car-insurance/comprehensive/",
  "/car-insurance/comprehensive/what-is-comprehensive-car-insurance/",
  "/car-insurance/comprehensive-vs-third-party/",
  "/car-insurance/cover-note/",
  "/car-insurance/ctp-vs-comprehensive/",
  "/car-insurance/ctp-vs-third-party/",
  "/car-insurance/deals/",
  "/car-insurance/electric-vehicles/",
  "/car-insurance/excess/",
  "/car-insurance/guides/reduce-car-insurance-premium/",
  "/car-insurance/hail-damage/",
  "/car-insurance/how-is-car-insurance-calculated/",
  "/car-insurance/hybrid-vehicle/",
  "/car-insurance/import/",
  "/car-insurance/learner-driver/",
  "/car-insurance/modified-cars/",
  "/car-insurance/multi-car/",
  "/car-insurance/new-car-insurance/",
  "/car-insurance/no-claim-bonus/",
  "/car-insurance/not-fault-claim/",
  "/car-insurance/not-fault-no-insurance/",
  "/car-insurance/p-platers/",
  "/car-insurance/pay-as-you-drive/",
  "/car-insurance/pensioners/",
  "/car-insurance/ppsr-car-history-check/",
  "/car-insurance/renewal/",
  "/car-insurance/rental-car/",
  "/car-insurance/resolving-disputes/",
  "/car-insurance/rideshare-insurance/",
  "/car-insurance/save-money-on-car-insurance/",
  "/car-insurance/short-term/",
  "/car-insurance/socials-feb-2025/",
  "/car-insurance/students/",
  "/car-insurance/switching-insurers/",
  "/car-insurance/telematics-black-box/",
  "/car-insurance/third-party-fire-theft-insurance/",
  "/car-insurance/third-party-property-damage-insurance/",
  "/car-insurance/types/",
  "/car-insurance/what-is-car-insurance/",
  "/car-insurance/why-pay-higher-premiums/",
  "/car-insurance/windscreen-glass-cover/",
  "/car-insurance/women/",
  "/car-insurance/write-off-car/",
  "/car-insurance/young-drivers/",
  "/careers/",
  "/contact-us/",
  "/energy/",
  "/energy/bill-smoothing/",
  "/energy/demand-tariff/",
  "/energy/peak-and-off-peak-electricity/",
  "/energy/compare-act-electricity/",
  "/energy/compare-electricity-plans/",
  "/energy/compare-electricity-plans-in-victoria/",
  "/energy/compare-gas-plans/",
  "/energy/compare-nsw-electricity/",
  "/energy/compare-qld-electricity/",
  "/energy/compare-south-australia-electricity/",
  "/energy/connecting-utilities-when-moving-house/",
  "/energy/controlled-load/",
  "/energy/dealing-with-bill-shock/",
  "/energy/default-market-offer/",
  "/energy/electricity-meters/",
  "/energy/embedded-electricity-network/",
  "/energy/ev-charging-at-home/",
  "/energy/fixed-rate/",
  "/energy/gas-meters/",
  "/energy/gas-vs-electricity/",
  "/energy/guides/energy-guide-energy-efficient-appliances/",
  "/energy/guides/how-to-keep-your-house-cool-in-summer/",
  "/energy/guides/how-to-make-your-home-more-energy-efficient/",
  "/energy/guides/power-outages/",
  "/energy/hot-water-system/",
  "/energy/how-to-read-bills/",
  "/energy/how-to-save-electricity/",
  "/energy/load-shedding/",
  "/energy/lpg/",
  "/energy/medical-energy-rebate/",
  "/energy/moving-house-checklist/",
  "/energy/northern-territory-electricity/",
  "/energy/renewable-energy-options/",
  "/energy/same-day-electricity-connection/",
  "/energy/small-business/",
  "/energy/small-business/contracts-tariffs/",
  "/energy/small-business/electricity/",
  "/energy/small-business/gas/",
  "/energy/smart-meters/",
  "/energy/solar-batteries/",
  "/energy/solar-energy-in-australia/",
  "/energy/solar-feed-tariff/",
  "/energy/solar-panel-installation/",
  "/energy/state-energy-concession-information/",
  "/energy/tariffs/",
  "/energy/tasmania-electricity/",
  "/energy/types-of-gas/",
  "/energy/victorian-default-offer/",
  "/energy/virtual-power-plant/",
  "/energy/ways-to-track-your-energy-usage/",
  "/energy/western-australia-electricity/",
  "/energy/what-happens-when-i-switch-energy-providers/",
  "/fuel/",
  "/fuel/simples-fuel-app/",
  "/health-insurance/",
  "/health-insurance/bypass-surgery-cost/",
  "/health-insurance/about/hicaps/",
  "/health-insurance/access-gap-cover/",
  "/health-insurance/acl-surgery-cost/",
  "/health-insurance/age-based-discounts/",
  "/health-insurance/agreement-private-hospitals/",
  "/health-insurance/ambulance-cover/",
  "/health-insurance/angiogram-cost/",
  "/health-insurance/appendectomy-cost/",
  "/health-insurance/assisted-reproductive-services/",
  "/health-insurance/australian-capital-territory/",
  "/health-insurance/australian-government-rebate/claiming-your-rebate/",
  "/health-insurance/basic/",
  "/health-insurance/benefits-private-health-insurance/",
  "/health-insurance/breast-cancer/",
  "/health-insurance/breast-reduction-surgery-cost/",
  "/health-insurance/bronze/",
  "/health-insurance/cancel-health-insurance/",
  "/health-insurance/cataracts-surgery-cost/",
  "/health-insurance/categories/",
  "/health-insurance/chemotherapy-cost/",
  "/health-insurance/colonoscopy-cost/",
  "/health-insurance/combined-hospital-extras-cover/",
  "/health-insurance/commonwealth-seniors-health-card/",
  "/health-insurance/cosmetic-surgery/",
  "/health-insurance/cost-health-insurance/",
  "/health-insurance/cost-of-botox/",
  "/health-insurance/couples/",
  "/health-insurance/couples-starting-family/",
  "/health-insurance/day-surgery/",
  "/health-insurance/denture-cost/",
  "/health-insurance/dependent-children/",
  "/health-insurance/difference-between-hospital-and-extras/",
  "/health-insurance/do-i-need-health-insurance/",
  "/health-insurance/endoscopy-cost/",
  "/health-insurance/extras-reset/",
  "/health-insurance/factors-affect-premium/",
  "/health-insurance/families/",
  "/health-insurance/gastroscopy-cost/",
  "/health-insurance/gold/",
  "/health-insurance/hernia-surgery-cost/",
  "/health-insurance/insulin-pump-cost/",
  "/health-insurance/guides/poly-cystic-ovary-syndrome-the-pcos-guide/",
  "/health-insurance/guides/private-versus-public-its-all-in-the-details/",
  "/health-insurance/guides/womens-health-happy-healthy-feeling-great/",
  "/health-insurance/guides/your-guide-to-sports-injuries/",
  "/health-insurance/haemorrhoid-surgery-cost/",
  "/health-insurance/health-insurance-premium-rate-rise/",
  "/health-insurance/health-insurance-still-worth-50s/",
  "/health-insurance/hearing-aids-cost/",
  "/health-insurance/hip-replacement-surgery-cost/",
  "/health-insurance/hysterectomy-cost/",
  "/health-insurance/knee-arthroscopy-cost/",
  "/health-insurance/knee-replacement-cost/",
  "/health-insurance/laparoscopy-cost/",
  "/health-insurance/laser-eye-surgery-cost/",
  "/health-insurance/lhc-calculator/",
  "/health-insurance/lifetime-health-cover-loading/",
  "/health-insurance/major-dental/",
  "/health-insurance/major-dental/root-canal/",
  "/health-insurance/mature-couples-singles/",
  "/health-insurance/medicare-levy/",
  "/health-insurance/medicare-levy-surcharge/",
  "/health-insurance/medicare-levy-surcharge-calculator/",
  "/health-insurance/medicare-safety-net/",
  "/health-insurance/meerkat-hoodie-promotion-2025/",
  "/health-insurance/mental-health/",
  "/health-insurance/mri-cost/",
  "/health-insurance/nasal-turbinate-surgery-cost/",
  "/health-insurance/new-south-wales/",
  "/health-insurance/northern-territory/",
  "/health-insurance/not-for-profit-health-insurance/",
  "/health-insurance/offers/",
  "/health-insurance/ovarian-cancer/",
  "/health-insurance/pacemaker-cost/",
  "/health-insurance/pharmaceutical-benefits-scheme/",
  "/health-insurance/pre-existing-conditions/",
  "/health-insurance/pregnancy-birth-related-services/",
  "/health-insurance/queensland/",
  "/health-insurance/save-money-on-health-insurance/",
  "/health-insurance/schedule-a-call/",
  "/health-insurance/septoplasty-cost/",
  "/health-insurance/shoulder-surgery-cost/",
  "/health-insurance/silver/",
  "/health-insurance/single-parent-family/",
  "/health-insurance/singles/",
  "/health-insurance/sleep-study-cost/",
  "/health-insurance/specialist-doctors/",
  "/health-insurance/spinal-fusion-surgery-cost/",
  "/health-insurance/socials-feb-2025/",
  "/health-insurance/south-australia/",
  "/health-insurance/switching/",
  "/health-insurance/tasmania/",
  "/health-insurance/taxes/",
  "/health-insurance/tonsillectomy-cost/",
  "/health-insurance/tooth-extraction-cost/",
  "/health-insurance/top-tips-for-selecting-health-funds/",
  "/health-insurance/tubal-litigation-cost/",
  "/health-insurance/vasectomy-cost/",
  "/health-insurance/victoria/",
  "/health-insurance/waiting-periods/",
  "/health-insurance/weight-loss-surgery/",
  "/health-insurance/western-australia/",
  "/health-insurance/what-does-medicare-cover/",
  "/health-insurance/what-is-extras-cover/",
  "/health-insurance/what-is-extras-cover/chiropractic/",
  "/health-insurance/what-is-extras-cover/dental/",
  "/health-insurance/what-is-extras-cover/flexible-extras/",
  "/health-insurance/what-is-extras-cover/family-extras/",
  "/health-insurance/what-is-extras-cover/gym-rebates/",
  "/health-insurance/what-is-extras-cover/natural-remedies/",
  "/health-insurance/what-is-extras-cover/optical/",
  "/health-insurance/what-is-extras-cover/orthodontics/",
  "/health-insurance/what-is-extras-cover/physiotherapy/",
  "/health-insurance/what-is-hospital-cover/",
  "/health-insurance/what-is-hospital-cover/excess/",
  "/health-insurance/what-is-hospital-cover/inpatient-vs-outpatient/",
  "/health-insurance/what-is-hospital-cover/medical-gap/",
  "/health-insurance/wisdom-teeth/",
  "/health-insurance/worth-it/",
  "/health-insurance/young-singles/",
  "/health-insurance-call/",
  "/home-contents-insurance/",
  "/home-contents-insurance/apartment-insurance/",
  "/home-contents-insurance/art-insurance/",
  "/home-contents-insurance/australian-capital-territory/",
  "/home-contents-insurance/australian-capital-territory/canberra/",
  "/home-contents-insurance/building-insurance/",
  "/home-contents-insurance/certificate-of-currency/",
  "/home-contents-insurance/contents-insurance/",
  "/home-contents-insurance/deals/",
  "/home-contents-insurance/emergency-home-assist/",
  "/home-contents-insurance/guides/first-things-first-new-house-buyers/",
  "/home-contents-insurance/guides/guide-to-garage-sales/",
  "/home-contents-insurance/guides/home-contents-insurance-explained/",
  "/home-contents-insurance/guides/home-renovation-made-easy-guide-getting-right/",
  "/home-contents-insurance/guides/reduce-risk-theft-around-home/",
  "/home-contents-insurance/guides/renting-out-room/",
  "/home-contents-insurance/guides/the-complete-guide-for-first-time-renters/",
  "/home-contents-insurance/home-insurance/",
  "/home-contents-insurance/information/claims/",
  "/home-contents-insurance/information/cost-factors/",
  "/home-contents-insurance/information/excess/",
  "/home-contents-insurance/information/exclusions/",
  "/home-contents-insurance/information/how-much-should-i-insure-my-house-for/",
  "/home-contents-insurance/information/listed-and-defined-events/",
  "/home-contents-insurance/information/underinsurance/",
  "/home-contents-insurance/insurance-cover-for-bicycles/",
  "/home-contents-insurance/is-home-insurance-worth-it/",
  "/home-contents-insurance/jewellery-insurance/",
  "/home-contents-insurance/jewellery-insurance/ring-insurance/",
  "/home-contents-insurance/landlords-insurance/",
  "/home-contents-insurance/landlords-insurance/australian-capital-territory/",
  "/home-contents-insurance/landlords-insurance/new-south-wales/",
  "/home-contents-insurance/landlords-insurance/northern-territory/",
  "/home-contents-insurance/landlords-insurance/queensland/",
  "/home-contents-insurance/landlords-insurance/south-australia/",
  "/home-contents-insurance/landlords-insurance/tasmania/",
  "/home-contents-insurance/landlords-insurance/victoria/",
  "/home-contents-insurance/landlords-insurance/western-australia/",
  "/home-contents-insurance/new-south-wales/",
  "/home-contents-insurance/new-south-wales/sydney/",
  "/home-contents-insurance/northern-territory/",
  "/home-contents-insurance/northern-territory/darwin/",
  "/home-contents-insurance/queensland/",
  "/home-contents-insurance/queensland/brisbane/",
  "/home-contents-insurance/renters-insurance/",
  "/home-contents-insurance/seniors-home-insurance/",
  "/home-contents-insurance/south-australia/",
  "/home-contents-insurance/south-australia/adelaide/",
  "/home-contents-insurance/tasmania/",
  "/home-contents-insurance/tasmania/hobart/",
  "/home-contents-insurance/types/accidental-damage/",
  "/home-contents-insurance/types/fire-insurance/",
  "/home-contents-insurance/types/glass-window-replacement/",
  "/home-contents-insurance/types/motor-burnout-insurance/",
  "/home-contents-insurance/types/personal-effects/",
  "/home-contents-insurance/types/personal-effects/camera-insurance/",
  "/home-contents-insurance/types/personal-effects/laptop-insurance/",
  "/home-contents-insurance/types/personal-effects/phone-insurance/",
  "/home-contents-insurance/types/storm-damage/",
  "/home-contents-insurance/types/unoccupied-home-insurance/",
  "/home-contents-insurance/types/water-damage/",
  "/home-contents-insurance/victoria/",
  "/home-contents-insurance/victoria/melbourne/",
  "/home-contents-insurance/watch-insurance/",
  "/home-contents-insurance/western-australia/",
  "/home-contents-insurance/western-australia/perth/",
  "/home-contents-insurance/what-does-home-insurance-cover/",
  "/home-loans/apply-for-a-home-loan/",
  "/home-loans/buying-off-plan/",
  "/home-loans/calculators/",
  "/home-loans/calculators/borrowing-power-calculator/",
  "/home-loans/calculators/lvr-calculator/",
  "/home-loans/calculators/stamp-duty-calculator/",
  "/home-loans/capital-gains/",
  "/home-loans/comparison-rate/",
  "/home-loans/cooling-off-period/",
  "/home-loans/first-home-buyer/",
  "/home-loans/first-home-buyer/first-home-owner-grant/",
  "/home-loans/first-home-buyer/guarantor/",
  "/home-loans/first-home-buyer/home-loan-pre-approval/",
  "/home-loans/first-home-buyer/how-to-choose-a-conveyancer/",
  "/home-loans/first-home-buyer/ongoing-costs-of-home-ownership/",
  "/home-loans/gazumping/",
  "/home-loans/home-guarantee-scheme/",
  "/home-loans/home-guarantee-scheme/family-home-guarantee/",
  "/home-loans/home-guarantee-scheme/first-home-guarantee/",
  "/home-loans/home-guarantee-scheme/regional-home-guarantee/",
  "/home-loans/home-loan-features/",
  "/home-loans/household-expenditure-measure/",
  "/home-loans/investing/",
  "/home-loans/investing/understanding-negative-gearing-and-tax/",
  "/home-loans/lenders-mortgage-insurance/",
  "/home-loans/loan-types/",
  "/home-loans/loan-types/bridging-loan/",
  "/home-loans/loan-types/construction-loan/",
  "/home-loans/loan-types/fixed-rate-home-loans/",
  "/home-loans/loan-types/interest-home-loans/",
  "/home-loans/loan-types/renovation-loan/",
  "/home-loans/loan-types/variable-rate-home-loans/",
  "/home-loans/low-doc-home-loan/",
  "/home-loans/meet-the-team/",
  "/home-loans/mortgage-broker/",
  "/home-loans/mortgage-offset-accounts/",
  "/home-loans/mortgage-stress/",
  "/home-loans/negative-equity/",
  "/home-loans/online-home-loans/",
  "/home-loans/open-banking/",
  "/home-loans/rate-lock/",
  "/home-loans/real-estate-commission-fees/",
  "/home-loans/redraw/",
  "/home-loans/refinancing/",
  "/home-loans/refinancing/what-is-refinancing/",
  "/home-loans/revert-rate/",
  "/home-loans/settlement-process/",
  "/home-loans/split-loans/",
  "/home-loans/superannuation-deposit/",
  "/income-protection/",
  "/income-protection/information/",
  "/income-protection/information/tax/",
  "/income-protection/process/",
  "/income-protection/process/payout/",
  "/income-protection/self-employed/",
  "/income-protection/types/",
  "/income-protection/types/mortgage-protection-insurance/",
  "/income-protection/types/redundancy-cover/",
  "/international-money-transfers/",
  "/life-insurance/",
  "/life-insurance/family/",
  "/life-insurance/high-risk-individuals/",
  "/life-insurance/pre-existing-conditions/",
  "/life-insurance/seniors/",
  "/life-insurance/total-permanent-disablement/",
  "/life-insurance/trauma/",
  "/life-insurance/types/own-occupation-vs-any-occupation/",
  "/life-insurance/types/funeral-insurance/",
  "/life-insurance/types/term-life-insurance/",
  "/pet-insurance/",
  "/pet-insurance/cat-insurance/",
  "/pet-insurance/cat-insurance/breeds/",
  "/pet-insurance/cat-insurance/cat-price/",
  "/pet-insurance/cat-insurance/dental/",
  "/pet-insurance/cat-insurance/health-problems-symptoms/",
  "/pet-insurance/dental/",
  "/pet-insurance/dog-insurance/",
  "/pet-insurance/dog-insurance/ticks-fleas/",
  "/pet-insurance/dog-insurance/arthritis/",
  "/pet-insurance/dog-insurance/breeds/",
  "/pet-insurance/dog-insurance/breeds/independent/",
  "/pet-insurance/dog-insurance/breeds/large/",
  "/pet-insurance/dog-insurance/breeds/low-maintenance/",
  "/pet-insurance/dog-insurance/breeds/medium/",
  "/pet-insurance/dog-insurance/breeds/non-shedding/",
  "/pet-insurance/dog-insurance/breeds/small/",
  "/pet-insurance/dog-insurance/cancer/",
  "/pet-insurance/dog-insurance/dental/",
  "/pet-insurance/dog-insurance/dog-price/",
  "/pet-insurance/dog-insurance/family-child-friendly/",
  "/pet-insurance/dog-insurance/health-problems-symptoms/",
  "/pet-insurance/dog-insurance/guard-dog/",
  "/pet-insurance/dog-insurance/healthy-dog/",
  "/pet-insurance/dog-insurance/heatstroke/",
  "/pet-insurance/dog-insurance/skin-conditions/",
  "/pet-insurance/dog-insurance/toxic-foods/",
  "/pet-insurance/information/how-much-does-pet-insurance-cost/",
  "/pet-insurance/information/how-premiums-calculated/",
  "/pet-insurance/information/tips-for-choosing-pet-insurance/",
  "/pet-insurance/is-pet-insurance-worth-it/",
  "/pet-insurance/pre-existing-conditions/",
  "/pet-insurance/senior-pets/",
  "/pet-insurance/types/",
  "/pet-insurance/types/accident-illness-cover/",
  "/pet-insurance/types/accident-only-cover/",
  "/pet-insurance/types/comprehensive-insurance/",
  "/pet-insurance/vaccinations/",
  "/pet-insurance/vet-cost/",
  "/pet-insurance/waiting-period/",
  "/roadside-assistance/",
  "/travel-insurance/",
  "/travel-insurance/about/exclusions/",
  "/travel-insurance/about/how-to-claim/",
  "/travel-insurance/about/insurance-cost/",
  "/travel-insurance/already-overseas/",
  "/travel-insurance/annual-cover/",
  "/travel-insurance/backpackers/",
  "/travel-insurance/business/",
  "/travel-insurance/cancellation-travel-delay/",
  "/travel-insurance/couples/",
  "/travel-insurance/destinations/",
  "/travel-insurance/destinations/antarctica/",
  "/travel-insurance/destinations/australia/",
  "/travel-insurance/destinations/bali/",
  "/travel-insurance/destinations/brazil/",
  "/travel-insurance/destinations/cambodia/",
  "/travel-insurance/destinations/canada/",
  "/travel-insurance/destinations/chile/",
  "/travel-insurance/destinations/china/",
  "/travel-insurance/destinations/costa-rica/",
  "/travel-insurance/destinations/cuba/",
  "/travel-insurance/destinations/egypt/",
  "/travel-insurance/destinations/europe/",
  "/travel-insurance/destinations/fiji/",
  "/travel-insurance/destinations/france/",
  "/travel-insurance/destinations/germany/",
  "/travel-insurance/destinations/hawaii/",
  "/travel-insurance/destinations/hong-kong/",
  "/travel-insurance/destinations/india/",
  "/travel-insurance/destinations/indonesia/",
  "/travel-insurance/destinations/iran/",
  "/travel-insurance/destinations/ireland/",
  "/travel-insurance/destinations/italy/",
  "/travel-insurance/destinations/japan/",
  "/travel-insurance/destinations/latvia/",
  "/travel-insurance/destinations/malaysia/",
  "/travel-insurance/destinations/mexico/",
  "/travel-insurance/destinations/nepal/",
  "/travel-insurance/destinations/new-zealand/",
  "/travel-insurance/destinations/philippines/",
  "/travel-insurance/destinations/samoa/",
  "/travel-insurance/destinations/scotland/",
  "/travel-insurance/destinations/singapore/",
  "/travel-insurance/destinations/south-africa/",
  "/travel-insurance/destinations/south-america/",
  "/travel-insurance/destinations/south-korea/",
  "/travel-insurance/destinations/sri-lanka/",
  "/travel-insurance/destinations/thailand/",
  "/travel-insurance/destinations/turkey/",
  "/travel-insurance/destinations/uk/",
  "/travel-insurance/destinations/usa/",
  "/travel-insurance/destinations/vietnam/",
  "/travel-insurance/emergency-assistance/",
  "/travel-insurance/excess/",
  "/travel-insurance/guides/a-simple-guide-to-the-uk-working-holiday-visa/",
  "/travel-insurance/guides/backpackers-guide-to-south-america-on-a-shoestring/",
  "/travel-insurance/international-drivers-licence/",
  "/travel-insurance/luggage-baggage-insurance/",
  "/travel-insurance/medical-only/",
  "/travel-insurance/motorcycle-scooter-cover/",
  "/travel-insurance/non-australian-resident/",
  "/travel-insurance/one-way/",
  "/travel-insurance/over-65s/",
  "/travel-insurance/personal-liability-overseas/",
  "/travel-insurance/pre-existing-conditions/",
  "/travel-insurance/pre-existing-conditions/cancer/",
  "/travel-insurance/pre-existing-conditions/diabetes/",
  "/travel-insurance/pre-existing-conditions/heart-condition/",
  "/travel-insurance/reciprocal-health-care-agreement/",
  "/travel-insurance/skiers-insurance/",
  "/travel-insurance/surfing-cover/",
  "/travel-insurance/tips/carry-on-luggage/",
  "/travel-insurance/tips/children-travelling-alone/",
  "/travel-insurance/tips/long-term-insurance/",
  "/travel-insurance/tips/things-to-take-overseas/",
  "/travel-insurance/travel-insurance-compulsory/",
  "/travel-insurance/travel-insurance-online/",
  "/travel-insurance/types/adventurers/",
  "/travel-insurance/types/basic/",
  "/travel-insurance/types/credit-card-travel-insurance/",
  "/travel-insurance/types/cruise-insurance/",
  "/travel-insurance/types/essential/",
  "/travel-insurance/types/families/",
  "/travel-insurance/types/groups/",
  "/travel-insurance/types/hiking-trekking-mountaineering/",
  "/travel-insurance/types/medical-tourism/",
  "/travel-insurance/types/pregnancy/",
  "/travel-insurance/types/scuba-diving/",
  "/travel-insurance/types/seniors/",
  "/travel-insurance/types/students/",
  "/travel-insurance/volcano-ash-cloud-cover/",
  "/travel-insurance/what-is-excess/",
  "/travel-insurance/when-to-buy/",
  "/travel-insurance/why-do-i-need-travel-insurance/",
  "/travel-insurance/working-holiday/"
];

const newPPCRoutes = [
  "/health-insurance/best-price-promise-ppc-2/",
  "/health-insurance/best-price-promise-ppc-3/",
  "/health-insurance/best-price-promise-ppc-4/",
  "/health-insurance/compare-and-buy-health-insurance-ppc-1/",
  "/health-insurance/compare-health-insurance-plans-in-minutes-ppc-5/"
];

const newPageRoutes = newTrancheRoutes.concat(newPPCRoutes);

const baseCfPageRoute: Map<string, string> = new Map([
  ["dev", "dev.ctm-cf-page-enterprise-wordpress.pages.dev"],
  ["uat", "static.stg.xxx.xxx.xxx"],
  ["prod", "static.xxx.xxx.xxx"],
  ["pre-prod", "static.pre-prod.xxx.xxx.xxx"]
]);

function getRoute(env: string, hostname: string): string | undefined {
  if (hostname === "website.xxx.xxx.xxx") {
    return baseCfPageRoute.get("prod");
  }
  return baseCfPageRoute.get(env);
}

export function getWordpressRequestMiddleware(
  requestMiddleware: any,
  env: string,
  requestUrl: URL
): RequestMiddlewareRegistration[] {
  const allowedSubdomains = ["dev", "uat", "stg", "www", "website"];
  const subdomain: SubdomainInfo = getCTMSubdomain(requestUrl.hostname);
  let requestURLPath = requestUrl.pathname;
  requestURLPath += requestURLPath.endsWith("/") ? "" : "/";

  // Return no routes if not the main domain - whitelabels cannot have these routes: https://dev.azure.com/ctmaus/CTM/_workitems/edit/37578
  if (1 == subdomain.count && !allowedSubdomains.includes(subdomain.lastSub)) {
    return [];
  } else if (2 == subdomain.count && (!subdomain.lastSub.startsWith("cf-feat") || "dev" !== subdomain.raw[1])) {
    return [];
  } else if (2 < subdomain.count) {
    return [];
  } else {
    const params: URLSearchParams = requestUrl.searchParams;
    const isLegacyWordPressPreview: boolean =
      (params.get("page_id") !== "" || params.get("p") !== "") &&
      params.get("preview") === "true" &&
      requestUrl.pathname === "/";

    let requestMids: RequestMiddlewareRegistration[] = [
      [
        `${greedyRoutes.staticContentRoute}*`,
        [
          requestMiddleware.EmbedCFAccessHeaders,
          requestMiddleware.Router({
            destHost: getRoute(env, requestUrl.hostname),
            removeSubRoute: false,
            routePrefix: greedyRoutes.staticContentRoute
          })
        ]
      ],
      [
        `${greedyRoutes.preProdRoute}*`,
        [
          requestMiddleware.EmbedCFAccessHeaders,
          requestMiddleware.Router({
            destHost: getRoute("pre-prod", requestUrl.hostname),
            removeSubRoute: true,
            routePrefix: greedyRoutes.preProdRoute
          })
        ]
      ]
    ];

    // Check and Dynamic Add new Request Route as needed
    if (newPageRoutes.includes(requestURLPath)) {
      requestMids.push([
        requestURLPath,
        [
          requestMiddleware.EmbedCFAccessHeaders,
          requestMiddleware.Router({
            destHost: getRoute(env, requestUrl.hostname),
            removeSubRoute: false,
            routePrefix: requestURLPath
          })
        ]
      ]);
    }

    // to allow the Content Team to access legacy wordpress preview functionality ie www.xxx.xxx.xxx?page_id=111&preview=true,
    // we only route the base route to CF pages, if it is not a preview request
    if (!isLegacyWordPressPreview) {
      requestMids.push([
        `${singletonRoutes.baseRoute}`,
        [
          requestMiddleware.EmbedCFAccessHeaders,
          requestMiddleware.Router({
            destHost: getRoute(env, requestUrl.hostname),
            removeSubRoute: false,
            routePrefix: singletonRoutes.baseRoute
          })
        ]
      ]);
    }

    return requestMids;
  }
}

export function getWordpressResponseMiddleware(responseMiddleware: any, requestUrl: URL): ResponseMiddlewareRegistration[] {
  let WPResponses: ResponseMiddlewareRegistration[] = [];
  let requestURLPath = requestUrl.pathname;
  requestURLPath += requestURLPath.endsWith("/") ? "" : "/";

  // remove the CFAuthorization cookie from the Set-Cookie header, that was set by the zero trust application sitting in front of the CF page
  WPResponses = WPResponses.concat(
    Object.values(greedyRoutes).map((Route) => [`${Route}*`, [responseMiddleware.RemoveExtraCFAuth]])
  );
  WPResponses = WPResponses.concat(
    Object.values(singletonRoutes).map((Route: string) => [`${Route}`, [responseMiddleware.RemoveExtraCFAuth]])
  );

  if (newPageRoutes.includes(requestURLPath)) {
    WPResponses = WPResponses.concat([[`${requestURLPath}`, [responseMiddleware.RemoveExtraCFAuth]]]);
  }

  return WPResponses;
}
